[package]
name = "cs-199-final-project"
version = "0.0.1"
authors = ["Saad Ahmad and Daniel Murphy"]
edition = "2021"

[dependencies]
argon2 = "0.5.2"
chrono = "0.4.31"
rand = "0.8.5"
once_cell = "1.8.0"